version: "3.9"
services:
  nginx: # Gateway to do SSL termination
    image: docker.io/nginx:1.27.0-alpine
    ports:
      - 9999:443 # TLS listening on 443, safer to expose this to the outside world
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/ssl:/etc/nginx/ssl
  api:
    # image: localai/localai:latest-aio-cpu
    # For a specific version:
    # image: localai/localai:v2.16.0-aio-cpu
    # For Nvidia GPUs decomment one of the following (cuda11 or cuda12):
    # image: localai/localai:v2.16.0-aio-gpu-nvidia-cuda-11
    image: localai/localai:v2.16.0-aio-gpu-nvidia-cuda-12
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-11
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    healthcheck:
      test:
      - "CMD"
      - "curl"
      - "-f" 
      - "http://localhost:8080/readyz"
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 9998:8080 # HTTP listening on 8080, do not expose this to Internet
    env_file:
      - .env
    environment:
      - DEBUG=true
      - API_KEY=${API_KEY}  # If non-empty, clients must set OPENAI_API_KEY to connect
    volumes:
      - ./models:/build/models:cached
    deploy:
      resources:
        reservations:
          devices: # Enables GPU access
          - driver: nvidia
            count: 1
            capabilities: [gpu]
